# Generated by Django 3.0.8 on 2020-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmqtt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedstrings',
            name='string',
        ),
        migrations.AddField(
            model_name='receivedstrings',
            name='gyroX',
            field=models.CharField(default='', max_length=255, verbose_name='GYRO-X'),
        ),
        migrations.AddField(
            model_name='receivedstrings',
            name='gyroY',
            field=models.CharField(default='', max_length=255, verbose_name='GYRO-Y'),
        ),
        migrations.AddField(
            model_name='receivedstrings',
            name='gyroZ',
            field=models.CharField(default='', max_length=255, verbose_name='GYRO-Z'),
        ),
        migrations.AddField(
            model_name='receivedstrings',
            name='imuX',
            field=models.CharField(default='', max_length=255, verbose_name='IMU-X'),
        ),
        migrations.AddField(
            model_name='receivedstrings',
            name='imuY',
            field=models.CharField(default='', max_length=255, verbose_name='IMU-Y'),
        ),
        migrations.AddField(
            model_name='receivedstrings',
            name='imuZ',
            field=models.CharField(default='', max_length=255, verbose_name='IMU-Z'),
        ),
        migrations.AddField(
            model_name='receivedstrings',
            name='sensorName',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
