# Generated by Django 3.0.8 on 2020-10-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmqtt', '0002_auto_20201021_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrayName', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('sensorCount', models.CharField(default='0', max_length=2, verbose_name='Number of Sensor nodes')),
            ],
        ),
    ]
