# Generated by Django 3.0.8 on 2020-10-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmqtt', '0003_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeName', models.CharField(default='', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='arrayName',
            new_name='sensorName',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensorCount',
        ),
        migrations.AddField(
            model_name='sensor',
            name='xCoordinate',
            field=models.CharField(default='', max_length=255, verbose_name='X Coordinate'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='yCoordinate',
            field=models.CharField(default='', max_length=255, verbose_name='Y Coordinate'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='zCoordinate',
            field=models.CharField(default='', max_length=255, verbose_name='Z Coordinate'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmqtt.Node'),
        ),
    ]
