# Generated by Django 3.0.8 on 2020-10-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmqtt', '0004_auto_20201027_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceivedStrings',
            new_name='ReceivedString',
        ),
    ]
